CC := gcc
ARCH := X86_64

CFLAGS := -O2 -pthread -D_XOPEN_SOURCE=500 -D_POSIX_C_SOURCE=200112 -std=c11 -g -fno-strict-aliasing
CFLAGS += -D ATOMIC_BARRIERS -D $(ARCH)

LDFLAGS := -lm

BASEDIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

ifndef BASEDIR
$(error Please define the BASEDIR variable)
endif

x = *

$(TARGET): $(OBJS) $(EXTRADEPS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS) $(LDFLAGS)


bindCores: CFLAGS += -D BIND_CORES
bindCores: CFLAGS += -D_GNU_SOURCE
bindCores: TARGET := $(TARGET)-bindedCores
bindCores: $(TARGET)

bindThreads: CFLAGS += -D BIND_THREADS
bindThreads: CFLAGS += -D_GNU_SOURCE
bindThreads: TARGET := $(TARGET)-bindedThreads
bindThreads: $(TARGET)

debug: $(OBJS) $(EXTRADEPS)
	$(CC) $(CFLAGS) -g -o $(TARGET) $(OBJS) $(LDFLAGS)

clean:
	rm -rf *.o $(TARGET)*

semiclean:
	rm -rf *.o

%.o: %.c $(EXTRADEPS)
	$(CC) -c $(CFLAGS) $<	

