TARGET = RAYTRACE

OBJS = bbox.o cr.o env.o fbuf.o geo.o huprn.o husetup.o hutv.o isect.o \
	main.o matrix.o memory.o poly.o raystack.o shade.o sph.o trace.o \
	tri.o workpool.o

include ../../Makefile.config


bbox.c: rt.h
cr.c:	rt.h
env.c:	rt.h
fbuf.c: rt.h
geo.c:	rt.h
huprn.c: rt.h
husetup.c: rt.h
hutv.c: rt.h
isect.c: rt.h
main.c: rt.h
matrix.c: rt.h
memory.c: rt.h
poly.c: rt.h
raystack.c: rt.h
shade.c: rt.h
sph.c:	rt.h
trace.c: rt.h
tri.c:	rt.h
workpool.c: rt.h

