TARGET = RAYTRACE

OBJS = bbox.o cr.o env.o fbuf.o geo.o huprn.o husetup.o hutv.o isect.o \
	main.o matrix.o memory.o poly.o raystack.o shade.o sph.o trace.o \
	tri.o workpool.o

include ../../Makefile.config


bbox.c: bbox.c.in rt.h
cr.c:	cr.c.in rt.h
env.c:	env.c.in rt.h
fbuf.c: fbuf.c.in rt.h
geo.c:	geo.c.in rt.h
huprn.c: huprn.c.in rt.h
husetup.c: husetup.c.in rt.h
hutv.c: hutv.c.in rt.h
isect.c: isect.c.in rt.h
main.c: main.c.in rt.h
matrix.c: matrix.c.in rt.h
memory.c: memory.c.in rt.h
poly.c: poly.c.in rt.h
raystack.c: raystack.c.in rt.h
shade.c: shade.c.in rt.h
sph.c:	sph.c.in rt.h
trace.c: trace.c.in rt.h
tri.c:	tri.c.in rt.h
workpool.c: workpool.c.in rt.h

